[package]
name = "d3d9_hook_core"
publish.workspace = true
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
log.workspace = true
anyhow.workspace = true
windows.workspace = true
