[build]
target = "i686-pc-windows-gnu" # gnu by default

[alias]
build-d3d9 = "build --target i686-pc-windows-msvc --release"
build-client = "build --target i686-pc-windows-msvc --release -p injector_client_wrapper"
build-plugin = "build --target i686-pc-windows-msvc --release -p injector_server_plugin"

gnu-build-d3d9 = "build --target i686-pc-windows-gnu --release"
gnu-build-client = "build --target i686-pc-windows-gnu --release -p injector_client_wrapper"
gnu-build-plugin = "build --target i686-pc-windows-gnu --release -p injector_server_plugin"
